### ISSUE TITLE
Ensure Repeatability

### ISSUE THREAD

**Issue by hammacktony** [harpalsahota/bbaug#3]
Is there a way to set the seed so that I can recreate how the policies were selected? I would like to have some type of record of augmentations applied so I can verify my training steps in the future when I have more data.

**Comment by harpalsahota** [comment]
Yup, there is. The sub-policy is chosen by `random.choice`. You can get reproducible choices  by setting a random seed like so:

```python
import random
random.seed(42)
```

**Comment by harpalsahota** [comment]
Actually that still won't be deterministic due to a random probability calculation for each augmentation. I'll patch this is `v0.4.1`

**Comment by hammacktony** [comment]
Probably should have test(s) covering this as well.

**Comment by harpalsahota** [comment]
Yup, still in the `develop` branch. Tests will be added shortly

**Comment by harpalsahota** [comment]
Repeatability now achievable in `v0.4.1`
