### ISSUE TITLE
Apply augmentations on entire batch

### ISSUE THREAD

**Issue by hammacktony** [harpalsahota/bbaug#4]
Looking at the documentation, it seems that I would apply the augmentation one image at a time. Is there a way to apply this to an entire batch?

**Comment by harpalsahota** [comment]
If you look at the `example_run` notebook it provides an example using it in batches. There is only a single image in this dataset which is why only a single image is shown. Adding more images will result in the behaviour you want.

**Comment by hammacktony** [comment]
Ah okay. Couldn't determine that given a single image. Thanks!
